# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*'
      - '!README.md'
      - '!README_CN.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*'
      - '!README.md'
      - '!README_CN.md'
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Install dependencies
      run: |
        go mod tidy

    - name: Run tests
      run: |
        go test ./...

    - name: Build project
      run: |
        go build

  build-multiarch:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Build for multiple platforms
      run: |
        GOOS=linux GOARCH=amd64 go build -o FeasOJ-Backend-linux-amd64
        GOOS=linux GOARCH=arm64 go build -o FeasOJ-Backend-linux-arm64
        GOOS=windows GOARCH=amd64 go build -o FeasOJ-Backend-windows-amd64.exe
        GOOS=windows GOARCH=arm64 go build -o FeasOJ-Backend-windows-arm64.exe

    - name: Upload to GitHub Releases
      uses: actions/upload-artifact@v4
      with:
        name: FeasOJ-Backend-${{ github.run_number }}
        path: |
          FeasOJ-Backend-linux-amd64
          FeasOJ-Backend-linux-arm64
          FeasOJ-Backend-windows-amd64.exe
          FeasOJ-Backend-windows-arm64.exe
